name = "AoC-2023"
author = "Jacob Williams"
copyright  = "Copyright (c) 2023, Jacob Williams"
license = "BSD-3"
description = "Advent of Code 2023 with Fortran"
homepage = "https://github.com/jacobwilliams/AoC-2023"
keywords = ["AOC"]

# [dependencies]
# argv-fortran = { git="https://github.com/jacobwilliams/argv-fortran.git" }
# json-fortran = { git="https://github.com/jacobwilliams/json-fortran.git", tag = "8.3.0" }
# daglib = { git="https://github.com/jacobwilliams/daglib" }
# pikaia = { git="https://github.com/jacobwilliams/pikaia.git", tag = "2.0.0" }

[build]
auto-executables = true
auto-examples = true
auto-tests = true

[library]
source-dir = "src"

[install]
library = false
