add_edge – AoC-2023
add_edge Subroutine
12 statements
Source File
private subroutine add_edge(me, edge)
add an edge index for this vertex
Type Bound
vertex
Arguments
Type Intent Optional Attributes Name
class(vertex), intent(inout) :: me
integer, intent(in) :: edge
Called by
Source Code
    subroutine add_edge(me,edge)
    class(vertex),intent(inout) :: me
    integer,intent(in) :: edge
    if (allocated(me%edges)) then
        if (.not. any (edge==me%edges)) then
            me%edges = [me%edges, edge]  ! auto lhs reallocation
        end if
    else
        allocate(me%edges(1))
        me%edges = [edge]
    end if
    end subroutine add_edge
Call graph
set_edge_vector calls add_edge
dag_set_edges calls set_edges
dag_example calls dag_set_edges
problem_25 calls dag_set_edges