beats – AoC-2023
beats Function
19 statements
Source File
function beats(hand1, hand2, with_jokers)
return true if hand1 beats hand2 (has a higher score)
Arguments
Type Intent Optional Attributes Name
class(hand), intent(inout) :: hand1
class(hand), intent(inout) :: hand2
logical, intent(in) :: with_jokers
if considering jokers
Return Value logical
Calls
Called by
Source Code
    logical function beats(hand1, hand2, with_jokers)
        !! return true if hand1 beats hand2 (has a higher score)
        class(hand),intent(inout) :: hand1, hand2
        logical,intent(in) :: with_jokers !! if considering jokers
        integer :: i
        associate(h1 => hand1%cards, h2 => hand2%cards)
            ! recompute type if it hasn't already been computed
            if (hand1%type==0) hand1%type = hand_type(hand1, with_jokers)
            if (hand2%type==0) hand2%type = hand_type(hand2, with_jokers)
            if (hand1%type==hand2%type) then
                ! lower index is stronger
                do i = 1, 5
                    if (h1(i)/=h2(i)) then
                        beats = index_in_cards(h1(i),with_jokers) < &
                                index_in_cards(h2(i),with_jokers) ! lower is stronger
                        return
                    end if
                end do
            else
                ! one hand beat the other
                beats = hand1%type < hand2%type  ! lower score is better (1-7)
            end if
        end associate
    end function beats
Call graph
beats calls hand_type, index_in_cards
hand_type calls unique
unique calls unique32, unique64
unique32 calls sort
unique64 calls sort
sort calls sort_ascending, sort_ascending_64
sort_ascending calls swap
sort_ascending_64 calls swap64
swap calls swap64, swap32, swap_str
problem_7b calls beats