clock_end – AoC-2023
clock_end Subroutine
10 statements
Source File
private subroutine clock_end(me, case_str)
Print runtime in milliseconds form the start of the clock.
Type Bound
clock
Arguments
Type Intent Optional Attributes Name
class(clock), intent(inout) :: me
character(len=*), intent(in) :: case_str
description of the case
Called by
Source Code
    subroutine clock_end(me, case_str)
        class(clock),intent(inout) :: me
        character(len=*),intent(in) :: case_str !! description of the case
        integer :: itime !! time in integer milliseconds
        call system_clock(me%end)
        itime = int(1000*(me%end - me%begin) / real(me%rate, wp))
        write(*,'(a,I4,a)') trim(case_str)//' runtime: ', itime, ' ms'
        write(*,'(a)') '---------------------------'
        write(*,*) ''
    end subroutine clock_end
Call graph
problem_1 calls clock_end
problem_10 calls clock_end
problem_11 calls clock_end
problem_12 calls clock_end
problem_12b calls clock_end
problem_13 calls clock_end
problem_15 calls clock_end
problem_16 calls clock_end
problem_17 calls clock_end
problem_18 calls clock_end
problem_19 calls clock_end
problem_19b calls clock_end
problem_2 calls clock_end
problem_21 calls clock_end
problem_22 calls clock_end
problem_23 calls clock_end
problem_24 calls clock_end
problem_25 calls clock_end
problem_3 calls clock_end
problem_4 calls clock_end
problem_5 calls clock_end
problem_6 calls clock_end
problem_7 calls clock_end
problem_8 calls clock_end
problem_9 calls clock_end