clock_start – AoC-2023
clock_start Subroutine
4 statements
Source File
private subroutine clock_start(me)
Start the clock
Type Bound
clock
Arguments
Type Intent Optional Attributes Name
class(clock), intent(inout) :: me
Called by
Source Code
    subroutine clock_start(me)
        class(clock),intent(inout) :: me
        call system_clock(me%begin, me%rate)
    end subroutine clock_start
Call graph
problem_1 calls clock_start
problem_10 calls clock_start
problem_11 calls clock_start
problem_12 calls clock_start
problem_12b calls clock_start
problem_13 calls clock_start
problem_15 calls clock_start
problem_16 calls clock_start
problem_17 calls clock_start
problem_18 calls clock_start
problem_19 calls clock_start
problem_19b calls clock_start
problem_2 calls clock_start
problem_21 calls clock_start
problem_22 calls clock_start
problem_23 calls clock_start
problem_24 calls clock_start
problem_25 calls clock_start
problem_3 calls clock_start
problem_4 calls clock_start
problem_5 calls clock_start
problem_6 calls clock_start
problem_7 calls clock_start
problem_8 calls clock_start
problem_9 calls clock_start