d2norm – AoC-2023
d2norm Function
12 statements
Source File
private pure function d2norm(a, b)
Returns with precautions to avoid overflow.
History
21 Mar 1990: First version.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: a
real(kind=wp), intent(in) :: b
Return Value real(kind=wp)
Called by
Source Code
   pure function d2norm( a, b )
   real(wp) :: d2norm
   real(wp),intent(in) :: a
   real(wp),intent(in) :: b
   real(wp) :: scale
   scale  = abs( a ) + abs( b )
   if (scale == zero) then
      d2norm = zero
   else
      d2norm = scale * sqrt( (a/scale)**2   +  (b/scale)**2 )
   end if
   end function d2norm
Call graph
lsqr calls d2norm
solve_ez calls lsqr
test calls lsqr
lsqr_test calls test
nlesolver_solver calls solve_ez
main calls solve_ez, lsqr_test
nlesolver_test_1 calls nlesolver_solver
sparse_test calls nlesolver_solver