destroy_cache – AoC-2023
destroy_cache Subroutine
4 statements
Source File
private subroutine destroy_cache(me)
Destroy a cache.
Type Bound
function_cache
Arguments
Type Intent Optional Attributes Name
class(function_cache), intent(out) :: me
Called by
Source Code
    subroutine destroy_cache(me)
    implicit none
    class(function_cache),intent(out) :: me
    end subroutine destroy_cache
Call graph
initialize_cache calls destroy_cache
initialize_numdiff calls destroy_cache, initialize_cache
initialize_numdiff_for_diff calls destroy_cache, initialize_cache
test1 calls initialize_numdiff, initialize_numdiff_for_diff