drop – AoC-2023
drop Subroutine
12 statements
Source File
subroutine drop()
continue forward in time until all the bricks settle.
Arguments
None
Calls
Called by
Source Code
    subroutine drop()
        !! continue forward in time until all the bricks settle.
        logical :: moved, tmp_moved
        integer(ip) :: i
        do
            moved = .false.
            do i = 1, n_lines
                call move_piece_down(i, tmp_moved)
                if (tmp_moved) moved = .true. ! at least one was moved
            end do
            if (.not. moved) exit ! done moving all the pieces
        end do
    end subroutine drop
Call graph
drop calls move_piece_down
move_piece_down calls get_pieces_below, update_array
get_pieces_below calls unique
unique calls unique32, unique64
unique32 calls sort
unique64 calls sort
sort calls sort_ascending, sort_ascending_64
sort_ascending calls swap
sort_ascending_64 calls swap64
swap calls swap64, swap32, swap_str
initialize calls drop
problem_22 calls initialize