expand_vector – AoC-2023
expand_vector Subroutine
29 statements
Source File
private pure subroutine expand_vector(vec, n, val, finished)
Add elements to the integer vector in chunks.
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), dimension(:), allocatable :: vec
integer, intent(inout) :: n
counter for last element added to vec. must be initialized to size(vec) (or 0 if not allocated) before first call
integer, intent(in), optional :: val
the value to add to vec
logical, intent(in), optional :: finished
set to true to return vec as its correct size (n)
Called by
Source Code
    pure subroutine expand_vector(vec,n,val,finished)
    integer,dimension(:),allocatable,intent(inout) :: vec
    integer,intent(inout)       :: n           !! counter for last element added to `vec`.
                                               !! must be initialized to `size(vec)`
                                               !! (or 0 if not allocated) before first call
    integer,intent(in),optional :: val         !! the value to add to `vec`
    logical,intent(in),optional :: finished    !! set to true to return `vec`
                                               !! as its correct size (`n`)
    integer,dimension(:),allocatable :: tmp  !! temporary array
    if (present(val)) then
        if (allocated(vec)) then
            if (n==size(vec)) then
                ! have to add another chunk:
                allocate(tmp(size(vec)+chunk_size))
                tmp(1:size(vec)) = vec
                call move_alloc(tmp,vec)
            end if
            n = n + 1
        else
            ! the first element:
            allocate(vec(chunk_size))
            n = 1
        end if
        vec(n) = val
    end if
    if (present(finished)) then
        if (finished) then
            ! set vec to actual size (n):
            if (allocated(tmp)) deallocate(tmp)
            allocate(tmp(n))
            tmp = vec(1:n)
            call move_alloc(tmp,vec)
        end if
    end if
    end subroutine expand_vector
Call graph
split1 calls expand_vector
split calls split1, split2
split2 calls split1
go calls split
initialize calls split
parse_nums64 calls split
parse_rule calls split
problem_12b calls split
problem_15 calls split
problem_19 calls split, parse_rule
problem_19b calls split, parse_rule
problem_2 calls split
problem_24 calls split
problem_25 calls split
problem_4 calls split
problem_7 calls split
parse calls parse_nums64
problem_12 calls go
problem_18 calls go
problem_22 calls initialize
problem_9 calls parse