get_pieces_below – AoC-2023
get_pieces_below Function
16 statements
Source File
function get_pieces_below(i) result(ipieces)
get set of pieces directly below piece i
Arguments
Type Intent Optional Attributes Name
integer(kind=ip), intent(in) :: i
Return Value integer(kind=ip), dimension(:), allocatable
Calls
Called by
Source Code
    function get_pieces_below(i) result(ipieces)
        !! get set of pieces directly below piece i
        integer(ip),intent(in) :: i
        integer(ip),dimension(:),allocatable :: ipieces
        integer(ip) :: x,y,z !! counter
        allocate(ipieces(0))
        do x = istart_array(i,1), iend_array(i,1)
            do y = istart_array(i,2), iend_array(i,2)
                do z = istart_array(i,3), iend_array(i,3)
                    if (z-1>0) then ! 0 is the floor
                        if (array(x,y,z-1)/=0) ipieces = [ipieces,array(x,y,z-1)] ! below this one
                    end if
                end do
            end do
        end do
        ipieces = unique(pack(ipieces, ipieces/=i)) ! exclude the ones in this piece
    end function get_pieces_below
Call graph
get_pieces_below calls unique
unique calls unique32, unique64
unique32 calls sort
unique64 calls sort
sort calls sort_ascending, sort_ascending_64
sort_ascending calls swap
sort_ascending_64 calls swap64
swap calls swap64, swap32, swap_str
get_all_pieces_below calls get_pieces_below, get_all_pieces_below
move_piece_down calls get_pieces_below
problem_22 calls get_pieces_below, get_all_pieces_below, initialize
drop calls move_piece_down
initialize calls drop