get_all_pieces_below – AoC-2023
get_all_pieces_below Function
24 statements
Source File
recursive function get_all_pieces_below(i, iskip) result(ipieces)
reursively get a list of all pieces below piece i
Arguments
Type Intent Optional Attributes Name
integer(kind=ip), intent(in) :: i
integer(kind=ip), intent(in) :: iskip
skip this one and it's children
Return Value integer(kind=ip), dimension(:), allocatable
Calls
Called by
Source Code
    recursive function get_all_pieces_below(i, iskip) result(ipieces)
        !! reursively get a list of all pieces below piece i
        integer(ip),intent(in) :: i
        integer(ip),intent(in) :: iskip !! skip this one and it's children
        integer(ip),dimension(:),allocatable :: ipieces
        integer :: j !! counter
        logical :: found
        integer(ip) :: idx
        integer(ip),dimension(:),allocatable :: tmp
        call below_cache%get([i,iskip],idx,ipieces,found)
        if (.not. found) then
            allocate(ipieces(0))
            if (i==iskip) return
            tmp = get_pieces_below(i)
            if (size(tmp)>0) then
                tmp = pack(tmp, tmp/=iskip) ! remove the skipped one
                ipieces = [ipieces, tmp] ! ones directly below
                do j = 1, size(tmp) ! go down the tree
                    ipieces = [ipieces, get_all_pieces_below(tmp(j),iskip=iskip)]
                end do
                ipieces = unique(ipieces)
            end if
           call below_cache%put(idx,[i,iskip],ipieces)
        end if
    end function get_all_pieces_below
Call graph
get_all_pieces_below calls get_all_pieces_below, unique, get_from_cache, get_pieces_below, put_in_cache
unique calls unique32, unique64
get_from_cache calls vector_djb_hash
get_pieces_below calls unique
unique32 calls sort
unique64 calls sort
sort calls sort_ascending, sort_ascending_64
sort_ascending calls swap
sort_ascending_64 calls swap64
swap calls swap64, swap32, swap_str
problem_22 calls get_all_pieces_below