get_cell – AoC-2023
get_cell Function
9 statements
Source File
pure function get_cell(i, j) result(a)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip), intent(in) :: i
coordinates
integer(kind=ip), intent(in) :: j
coordinates
Return Value character(len=1)
Called by
Source Code
    pure function get_cell(i,j) result(a)
        integer(ip),intent(in) :: i,j !! coordinates
        character(len=1) :: a
        if (slopes) then
            a = array(i,j)
        else
            a = '.' ! ignore the slopes for part b
        end if
    end function get_cell
Call graph
build_graph calls get_cell, build_graph
go calls build_graph
problem_23 calls go