get_number – AoC-2023
get_number Function
14 statements
Source File
function get_number(i, j)
get the full number contining the character at i,j
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
integer, intent(in) :: j
Return Value integer(kind=int64)
Calls
Called by
Source Code
    integer(int64) function get_number(i,j)
        !! get the full number contining the character at i,j
        integer,intent(in) :: i,j
        jstart = j
        jend = j
        do
            if (array(i,jstart-1)=='.' .or. is_symbol(array(i,jstart-1))) exit
            jstart = jstart - 1
        end do
        do
            if (array(i,jend+1)=='.' .or. is_symbol(array(i,jend+1))) exit
            jend = jend + 1
        end do
        get_number = int(array(i, jstart:jend))
    end function get_number
Call graph
get_number calls is_symbol
is_symbol calls is_not_number
is_not_number calls is_number
check calls get_number
problem_3 calls get_number, check