get_all_pieces_above – AoC-2023
get_all_pieces_above Function
21 statements
Source File
recursive function get_all_pieces_above(i) result(ipieces)
reursively get a list of all pieces above piece i
Arguments
Type Intent Optional Attributes Name
integer(kind=ip), intent(in) :: i
Return Value integer(kind=ip), dimension(:), allocatable
Calls
Called by
Source Code
    recursive function get_all_pieces_above(i) result(ipieces)
        !! reursively get a list of all pieces above piece i
        integer(ip),intent(in) :: i
        integer(ip),dimension(:),allocatable :: ipieces
        integer :: j !! counter
        logical :: found
        integer(ip) :: idx
        call above_cache%get([i],idx,ipieces,found)
        if (.not. found) then
            allocate(ipieces(0))
            associate(tmp => get_pieces_above(i))
                if (size(tmp)>0) then
                    ipieces = [ipieces, tmp] ! ones directly above
                    do j = 1, size(tmp) ! go up the tree
                        ipieces = [ipieces, get_all_pieces_above(tmp(j))]
                    end do
                    ipieces = unique(ipieces)
                end if
            end associate
           call above_cache%put(idx,[i],ipieces)
        end if
    end function get_all_pieces_above
Call graph
get_all_pieces_above calls get_all_pieces_above, unique, get_from_cache, get_pieces_above, put_in_cache
unique calls unique32, unique64
get_from_cache calls vector_djb_hash
get_pieces_above calls unique
unique32 calls sort
unique64 calls sort
sort calls sort_ascending, sort_ascending_64
sort_ascending calls swap
sort_ascending_64 calls swap64
swap calls swap64, swap32, swap_str
problem_22 calls get_all_pieces_above