get_from_cache – AoC-2023
get_from_cache Subroutine
23 statements
Source File
private subroutine get_from_cache(me, x, i, f, found)
Check if the x vector is in the cache, if so return f. Note that only some of the elements may be present, so it will return the ones there are there, and indicate which ones were found.
Type Bound
function_cache
Arguments
Type Intent Optional Attributes Name
class(function_cache), intent(inout) :: me
integer(kind=ip), intent(in), dimension(:) :: x
independant variable vector
integer(kind=ip), intent(out) :: i
index in the hash table
integer(kind=ip), intent(out), dimension(:), allocatable :: f
f(x) from the cache (if it was found)
logical, intent(out) :: found
if x was found in the cache
Calls
Called by
Source Code
    subroutine get_from_cache(me,x,i,f,found)
    implicit none
    class(function_cache),intent(inout)      :: me
    integer(ip),dimension(:),intent(in)      :: x      !! independant variable vector
    integer(ip),intent(out)                  :: i      !! index in the hash table
    integer(ip),dimension(:),allocatable,intent(out) :: f      !! `f(x)` from the cache (if it was found)
    logical,intent(out)                      :: found  !! if `x` was found in the cache
    integer :: j !! counter
    ! initialize:
    found = .false.
    if (allocated(me%c)) then
        ! get index in the hash table:
        i = mod( abs(vector_djb_hash(x)), int(size(me%c),ip) )
        ! check the table:
        if (allocated(me%c(i)%x)) then
            if (size(me%c(i)%x)==size(x)) then
                if (all(me%c(i)%x==x)) then
                    found = .true.
                    f = me%c(i)%f
                end if
            end if
        end if
    else
        error stop 'Error: the cache has not been initialized.'
    end if
    end subroutine get_from_cache
Call graph
get_from_cache calls vector_djb_hash
get_all_pieces_above calls get_from_cache, get_all_pieces_above
get_all_pieces_below calls get_from_cache, get_all_pieces_below
go calls get_from_cache, ipoint, ipound
index_in_queue calls get_from_cache
check calls index_in_queue
ipoint calls go
ipound calls go
problem_12b calls go
problem_22 calls get_all_pieces_above, get_all_pieces_below
problem_17 calls check