get_pieces_above – AoC-2023
get_pieces_above Function
16 statements
Source File
function get_pieces_above(i) result(ipieces)
get set of pieces directly above piece i
Arguments
Type Intent Optional Attributes Name
integer(kind=ip), intent(in) :: i
Return Value integer(kind=ip), dimension(:), allocatable
Calls
Called by
Source Code
    function get_pieces_above(i) result(ipieces)
        !! get set of pieces directly above piece i
        integer(ip),intent(in) :: i
        integer(ip),dimension(:),allocatable :: ipieces
        integer(ip) :: x,y,z !! counter
        allocate(ipieces(0))
        do x = istart_array(i,1), iend_array(i,1)
            do y = istart_array(i,2), iend_array(i,2)
                do z = istart_array(i,3), iend_array(i,3)
                    if (z+1<=ubound(array,3)) then
                        if (array(x,y,z+1)/=0) ipieces = [ipieces,array(x,y,z+1)] ! above this one
                    end if
                end do
            end do
        end do
        ipieces = unique(pack(ipieces, ipieces/=i)) ! exclude the ones in this piece
    end function get_pieces_above
Call graph
get_pieces_above calls unique
unique calls unique32, unique64
unique32 calls sort
unique64 calls sort
sort calls sort_ascending, sort_ascending_64
sort_ascending calls swap
sort_ascending_64 calls swap64
swap calls swap64, swap32, swap_str
get_all_pieces_above calls get_pieces_above, get_all_pieces_above
problem_22 calls get_pieces_above, get_all_pieces_above