get_accepted – AoC-2023
get_accepted Function
4 statements
Source File
function get_accepted(p)
count of all the parts in the set
Arguments
Type Intent Optional Attributes Name
type(part), intent(in) :: p
Return Value integer(kind=ip)
Called by
Source Code
        integer(ip) function get_accepted(p)
            !! count of all the parts in the set
            type(part),intent(in) :: p
            get_accepted =  (1 + (p%xmas(1)%v(2) - p%xmas(1)%v(1)))* &
                            (1 + (p%xmas(2)%v(2) - p%xmas(2)%v(1)))* &
                            (1 + (p%xmas(3)%v(2) - p%xmas(3)%v(1)))* &
                            (1 + (p%xmas(4)%v(2) - p%xmas(4)%v(1)))
        end function get_accepted
Call graph
process calls get_accepted, process
problem_19b calls process