go – AoC-2023
go Subroutine
46 statements
Source File
subroutine go(case, filename, parta)
solve the case
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: case
case name for printing
character(len=*), intent(in) :: filename
input file to read
logical, intent(in) :: parta
if this is part a, then consider the slopes
Calls
Called by
Source Code
    subroutine go(case, filename, parta)
        !! solve the case
        character(len=*),intent(in) :: case !! case name for printing
        character(len=*),intent(in) :: filename !! input file to read
        logical,intent(in) :: parta !! if this is part a, then consider the slopes
        integer(ip),dimension(1) :: iloc
        integer(ip) :: istart, iend, idist, i, j
        ! initialize:
        max_dist = 0
        slopes = parta
        if (allocated(nodes))         deallocate(nodes)
        if (allocated(visited))       deallocate(visited)
        if (allocated(nodes_visited)) deallocate(nodes_visited)
        if (allocated(inodes))        deallocate(inodes)
        if (allocated(jnodes))        deallocate(jnodes)
        ! read the data file:
        array = read_file_to_char_array(filename)
        nrows = size(array,1)
        ncols = size(array,2)
        iloc = findloc(array(1,:), '.');     istart = iloc(1) ! get start and end columns
        iloc = findloc(array(nrows,:), '.'); iend   = iloc(1) !
        ! identify the coordinates of all the nodes:
        inodes = [1] ! start node
        jnodes = [istart]
        do i = 1, nrows
            do j = 1, ncols
                if (count_adjacent(i,j)>=3) then
                    inodes = [inodes, i]
                    jnodes = [jnodes, j]
                end if
            end do
        end do
        inodes = [inodes,nrows] ! end node
        jnodes = [jnodes,iend]
        total_nodes = size(inodes)
        ! for each node, find the other nodes they are
        ! connected to and the distances between them (the edges)
        allocate(nodes(total_nodes))
        allocate(visited(nrows, ncols))
        do i = 1, total_nodes
            visited = .false.
            idist = 0
            call build_graph(i,inodes(i),jnodes(i),idist,visited)
        end do
        ! start at first, and find the longest that gets to the last.
        ! recursively traverse the graph.
        visited = .false.
        allocate(nodes_visited(total_nodes)); nodes_visited = .false.
        call traverse(1_ip, 0_ip, nodes_visited)
        write(*,*) case, max_dist ! result for this case
    end subroutine go
Call graph
go calls build_graph, count_adjacent, read_file_to_char_array, traverse
build_graph calls build_graph, add_edge, get_cell, node_number
count_adjacent calls not_tree
read_file_to_char_array calls number_of_lines_in_file, read_line
traverse calls traverse
problem_23 calls go