integer_to_string – AoC-2023
integer_to_string Function
24 statements
Source File
private function integer_to_string(i, with_sign) result(str)
Convert an integer to a string.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
the integer
logical, intent(in), optional :: with_sign
also include the sign (default is False)
Return Value character(len=:), allocatable
integer converted to a string
Called by
Source Code
    function integer_to_string(i, with_sign) result(str)
    implicit none
    integer,intent(in)           :: i           !! the integer
    logical,intent(in),optional  :: with_sign   !! also include the sign (default is False)
    character(len=:),allocatable :: str         !! integer converted to a string
    integer :: istat !! `iostat` code for write statement
    character(len=100) :: tmp !!
    logical :: sgn !! local copy of `with_sign`
    if (present(with_sign)) then
        sgn = with_sign
    else
        sgn = .false.
    end if
    if (sgn) then
        write(tmp,'(SP,I100)',iostat=istat) i
    else
        write(tmp,'(I100)',iostat=istat) i
    end if
    if (istat == 0) then
        str = trim(adjustl(tmp))
    else
        str = '****'
    end if
    end function integer_to_string
Call graph
get_formula calls integer_to_string
set_numdiff_bounds calls integer_to_string
get_finite_diff_formula calls get_formula
initialize_numdiff calls set_numdiff_bounds
initialize_numdiff_for_diff calls set_numdiff_bounds
test1 calls get_formula, get_finite_diff_formula, initialize_numdiff, initialize_numdiff_for_diff
test2 calls get_finite_diff_formula