ipoint – AoC-2023
ipoint Function
9 statements
Source File
recursive function ipoint(ipattern, ints)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip), intent(in), dimension(:) :: ipattern
first char is a .
integer(kind=ip), intent(in), dimension(:) :: ints
Return Value integer(kind=ip)
Calls
Called by
Source Code
        recursive integer(ip) function ipoint(ipattern,ints)
            integer(ip),dimension(:),intent(in) :: ipattern !! first char is a .
            integer(ip),dimension(:),intent(in) :: ints
            if (size(ipattern)<=1) then
                ipoint = go([integer(ip) ::], ints) ! done, pass in empty array
            else
                ipoint = go(ipattern(2:), ints) ! skip it and go to next one
            end if
        end function ipoint
Call graph
ipoint calls go
go calls ipoint, get_from_cache, ipound, put_in_cache
get_from_cache calls vector_djb_hash
ipound calls go, ints_tmp, ipattern_tmp
problem_12b calls go