is_not_number – AoC-2023
is_not_number Function
4 statements
Source File
public function is_not_number(c)
returns true if the character is not a number.
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: c
Return Value logical
Calls
Called by
Source Code
    logical function is_not_number(c)
    character(len=1),intent(in) :: c
    is_not_number = .not. is_number(c)
    end function is_not_number
Call graph
is_not_number calls is_number
is_symbol calls is_not_number
problem_3 calls is_not_number, is_symbol, get_number, check
get_number calls is_symbol
check calls get_number