is_number – AoC-2023
is_number Function
4 statements
Source File
public function is_number(c)
returns true if the character is a number from 0 to 9.
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: c
Return Value logical
Called by
Source Code
    logical function is_number(c)
    character(len=1),intent(in) :: c
    is_number = c >= '0' .and. c <= '9'
    end function is_number
Call graph
check calls is_number, get_number
is_not_number calls is_number
is_symbol calls is_not_number
problem_3 calls check, is_not_number, is_symbol, get_number
get_number calls is_symbol