lsqr_test – AoC-2023
lsqr_test Subroutine
31 statements
Source File
public subroutine lsqr_test()
Unit test.
Arguments
None
Calls
Called by
Source Code
    subroutine lsqr_test()
    integer :: iunit,nbar,nduplc,n,m,ndamp,npower
    real(wp) :: damp
    type(test_solver) :: solver
    open( newunit=iunit, file='LSQR.LIS', status='REPLACE' )
    solver%nout = iunit
    nbar   = 1000
    nduplc = 40
    m = 2*nbar
    n = nbar
    do ndamp = 2, 7
        npower = ndamp
        damp   = 10.0_wp**(-ndamp-6)
        call solver%test( m, n, nduplc, npower, damp )
    end do
    m = nbar
    n = nbar
    do ndamp = 2, 7
        npower = ndamp
        damp   = 10.0_wp**(-ndamp-6)
        call solver%test( m, n, nduplc, npower, damp )
    end do
    m = nbar
    n = 2*nbar
    do ndamp = 2, 7
        npower = ndamp
        damp   = 10.0_wp**(-ndamp-6)
        call solver%test( m, n, nduplc, npower, damp )
    end do
    close(iunit)
    end subroutine lsqr_test
Call graph
lsqr_test calls test
test calls 4, acheck, dcopy, dnrm2, lsqr, lstp, xcheck
acheck calls dcopy, dnrm2, aprod, ddot, dscal
lsqr calls dcopy, dnrm2, aprod, d2norm, dscal
lstp calls dcopy, dnrm2, aprod1, dscal, hprod
xcheck calls dcopy, dnrm2, aprod, dscal
aprod1 calls hprod
main calls lsqr_test