match – AoC-2023
match Function
23 statements
Source File
function match(line, ints)
Arguments
Type Intent Optional Attributes Name
character(len=:), intent(inout), allocatable :: line
integer, intent(in), dimension(:) :: ints
Return Value logical
Calls
Called by
Source Code
    logical function match(line, ints)
        character(Len=:),allocatable,intent(inout) :: line
        integer,dimension(:),intent(in) :: ints
        type(string),dimension(:),allocatable :: vals
        integer :: i
        integer,dimension(:),allocatable :: itmp
        ! replaces any consecutive spaces with one space
        do
            if (index(line, '  ')>0) then
                call replace_alloc(line,'  ',' ')
            else
                exit
            end if
        end do
        vals = split(line,' ')
        match = size(vals) == size(ints)
        if (match) then
            allocate(itmp(size(vals)))
            do i = 1, size(vals)
                itmp(i) = len(vals(i)%str)   ! # # ###
            end do
            match = all(itmp == ints)
        end if
    end function match
Call graph
match calls split, replace_alloc
split calls split1, split2
split1 calls expand_vector
split2 calls split1
test calls match, test
problem_12 calls test