move_piece_down – AoC-2023
move_piece_down Subroutine
13 statements
Source File
subroutine move_piece_down(i, moved)
move a piece down (fall one square) if it can be moved
Arguments
Type Intent Optional Attributes Name
integer(kind=ip), intent(in) :: i
piece number
logical, intent(out) :: moved
if it was actually movec
Calls
Called by
Source Code
    subroutine move_piece_down(i, moved)
        !! move a piece down (fall one square) if it can be moved
        integer(ip),intent(in) :: i !! piece number
        logical,intent(out) :: moved !! if it was actually movec
        moved = .false.
        if (size(get_pieces_below(i))==0) then ! can only move if nothing below
            if (istart_array(i,3)>1 .and. iend_array(i,3)>1) then
                istart_array(i,3) = istart_array(i,3) - 1
                iend_array(i,3)   = iend_array(i,3)   - 1
                moved = .true.
                call update_array()
            end if
        end if
    end subroutine move_piece_down
Call graph
move_piece_down calls get_pieces_below, update_array
get_pieces_below calls unique
unique calls unique32, unique64
unique32 calls sort
unique64 calls sort
sort calls sort_ascending, sort_ascending_64
sort_ascending calls swap
sort_ascending_64 calls swap64
swap calls swap64, swap32, swap_str
drop calls move_piece_down
initialize calls drop
problem_22 calls initialize