number_of_lines_in_file – AoC-2023
number_of_lines_in_file Function
14 statements
Source File
public function number_of_lines_in_file(iunit) result(n_lines)
Returns the number of lines in a file (assumed to be open)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iunit
the file unit number (assumed to be open)
Return Value integer
the number of lines in the file
Called by
Source Code
    function number_of_lines_in_file(iunit) result(n_lines)
    integer,intent(in)  :: iunit  !! the file unit number
                                  !! (assumed to be open)
    integer :: n_lines  !! the number of lines in the file
    character(len=1) :: tmp
    integer :: istat
    rewind(iunit)
    n_lines = 0
    do
        read(iunit,fmt='(A1)',iostat=istat) tmp
        if (is_iostat_end(istat)) exit
        n_lines = n_lines + 1
    end do
    rewind(iunit)
    end function number_of_lines_in_file
Call graph
go calls number_of_lines_in_file, read_file_to_char_array
initialize calls number_of_lines_in_file
read_file_to_char_array calls number_of_lines_in_file
read_file_to_int_array calls number_of_lines_in_file
read_file_to_integer64_array calls number_of_lines_in_file
read_file_to_integer_array calls number_of_lines_in_file
problem_1 calls number_of_lines_in_file
problem_12b calls number_of_lines_in_file
problem_13 calls number_of_lines_in_file
problem_19 calls number_of_lines_in_file
problem_19b calls number_of_lines_in_file
problem_2 calls number_of_lines_in_file
problem_24 calls number_of_lines_in_file
problem_25 calls number_of_lines_in_file
problem_4 calls number_of_lines_in_file
problem_5 calls number_of_lines_in_file
problem_7 calls number_of_lines_in_file
problem_8 calls number_of_lines_in_file
problem_9 calls number_of_lines_in_file
problem_10 calls read_file_to_char_array
problem_12 calls go
problem_16 calls read_file_to_char_array
problem_17 calls read_file_to_int_array
problem_18 calls go
problem_21 calls read_file_to_char_array
problem_22 calls initialize
problem_3 calls read_file_to_char_array
problem_11 calls go
problem_23 calls go