parse_rule – AoC-2023
parse_rule Function
27 statements
Source File
function parse_rule(s) result(r)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: s
Return Value type(rule)
Calls
Called by
Source Code
        function parse_rule(s) result(r)
            character(len=*),intent(in) :: s
            type(rule) :: r
            type(string),dimension(:),allocatable :: v
            character(len=*),parameter :: xmas = 'xmas' ! 1,2,3,4
            if (s=='A') then
                r%accept = .true.
            else if (s=='R') then
                r%reject = .true.
            else
                if (index(s,'>')>0) then
                    v = split(s(3:), ':') ! example: a<2006:qkq
                    r%operator_arg = index(xmas,s(1:1))
                    r%operator = 2
                    r%operator_val = int(v(1)%str)
                    r%goto = v(2)%str ! can be a workflow or A or R
                else if (index(s,'<')>0) then
                    v = split(s(3:), ':')
                    r%operator_arg = index(xmas,s(1:1))
                    r%operator = 1
                    r%operator_val = int(v(1)%str)
                    r%goto = v(2)%str ! can be a workflow or A or R
                else
                    r%goto = s  ! it's a workflow name
                end if
            end if
        end function parse_rule
Call graph
parse_rule calls split
split calls split1, split2
split1 calls expand_vector
split2 calls split1
problem_19 calls parse_rule