parse_nums64 – AoC-2023
parse_nums64 Function
5 statements
Source File
private function parse_nums64(line) result(ints)
parse space-deliminated int64 sequence (positive or negative)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: line
Return Value integer(kind=int64), dimension(:), allocatable
Calls
Called by
Source Code
    function parse_nums64(line) result(ints)
        character(len=*),intent(in) :: line
        integer(int64),dimension(:),allocatable :: ints ! array of integers
        ints = int(split(line, ' '))
    end function parse_nums64
Call graph
parse_nums64 calls split
split calls split1, split2
split1 calls expand_vector
split2 calls split1
parse calls parse_nums64
problem_9 calls parse