put_in_cache – AoC-2023
put_in_cache Subroutine
18 statements
Source File
private subroutine put_in_cache(me, i, x, f)
Put a value into the cache.
Type Bound
function_cache
Arguments
Type Intent Optional Attributes Name
class(function_cache), intent(inout) :: me
integer(kind=ip), intent(in) :: i
index in the hash table
integer(kind=ip), intent(in), dimension(:) :: x
independant variable vector
integer(kind=ip), intent(in) :: f
function
Called by
Source Code
    subroutine put_in_cache(me,i,x,f)
    implicit none
    class(function_cache),intent(inout) :: me
    integer(ip),intent(in)              :: i    !! index in the hash table
    integer(ip),dimension(:),intent(in) :: x    !! independant variable vector
    integer(ip),intent(in)              :: f    !! function
    integer(ip),parameter :: null = huge(1) !! an unusual value to initialize arrays
    if (allocated(me%c)) then
        if (i<=size(me%c)) then
            ! add to the cache
            me%c(i)%x = x
            me%c(i)%f = f
        else
            error stop 'Error: invalid index in hash table.'
        end if
    else
        error stop 'Error: the cache has not been initialized.'
    end if
    end subroutine put_in_cache
Call graph
go calls put_in_cache, ipoint, ipound
index_in_queue calls put_in_cache
check calls index_in_queue
ipoint calls go
ipound calls go
problem_12b calls go
problem_17 calls check