raise_exception – AoC-2023
raise_exception Subroutine
10 statements
Source File
private subroutine raise_exception(me, istat, routine, error_msg)
Raise an exception.
Type Bound
numdiff_type
Arguments
Type Intent Optional Attributes Name
class(numdiff_type), intent(inout) :: me
integer, intent(in) :: istat
error code.
character(len=*), intent(in) :: routine
the routine where the error was raised.
character(len=*), intent(in) :: error_msg
error message string.
Called by
Source Code
    subroutine raise_exception(me,istat,routine,error_msg)
    implicit none
    class(numdiff_type),intent(inout) :: me
    integer,intent(in)          :: istat      !! error code.
    character(len=*),intent(in) :: routine    !! the routine where the error was raised.
    character(len=*),intent(in) :: error_msg  !! error message string.
    me%istat = istat
    me%error_msg = 'Error in '//trim(routine)//' : '//trim(error_msg)
    me%exception_raised = .true.
    end subroutine raise_exception
Call graph
compute_jacobian calls raise_exception, compute_perturbation_vector
compute_jacobian_partitioned calls raise_exception
compute_jacobian_standard calls raise_exception
compute_jacobian_with_diff calls raise_exception
compute_perturb_vector calls raise_exception
compute_sparsity_random calls raise_exception
compute_sparsity_random_2 calls raise_exception, compute_jacobian_for_sparsity
initialize_numdiff calls raise_exception, set_numdiff_bounds, set_sparsity_mode
initialize_numdiff_for_diff calls raise_exception, set_numdiff_bounds, set_sparsity_mode
set_numdiff_bounds calls raise_exception
set_numdiff_sparsity_bounds calls raise_exception
set_sparsity_mode calls raise_exception, set_numdiff_sparsity_bounds
set_sparsity_pattern calls raise_exception
compute_jacobian_dense calls compute_jacobian
compute_jacobian_times_vector calls compute_jacobian
compute_perturbation_vector calls compute_perturb_vector
compute_sparsity_perturbation_vector calls compute_perturb_vector
test1 calls compute_jacobian, initialize_numdiff, initialize_numdiff_for_diff
test2 calls compute_jacobian
compute_jacobian_for_sparsity calls compute_sparsity_perturbation_vector