read_line – AoC-2023
read_line Function
28 statements
Source File
public function read_line(iunit, status_ok) result(line)
Reads the next line from a file.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iunit
logical, intent(out), optional :: status_ok
true if no problems
Return Value character(len=:), allocatable
Called by
Source Code
    function read_line(iunit,status_ok) result(line)
    integer,intent(in) :: iunit
    character(len=:),allocatable :: line
    logical,intent(out),optional :: status_ok !! true if no problems
    integer :: nread  !! character count specifier for read statement
    integer :: istat  !! file read io status flag
    character(len=chunk_size) :: buffer !! the file read buffer
    nread  = 0
    buffer = ''
    line   = ''
    if (present(status_ok)) status_ok = .true.
    do
        ! read in the next block of text from the line:
        read(iunit,fmt='(A)',advance='NO',size=nread,iostat=istat) buffer
        if (IS_IOSTAT_END(istat) .or. IS_IOSTAT_EOR(istat)) then
            ! add the last block of text before the end of record
            if (nread>0) line = line//buffer(1:nread)
            exit
        else if (istat==0) then ! all the characters were read
            line = line//buffer  ! add this block of text to the string
        else  ! some kind of error
            if (present(status_ok)) then
                status_ok = .false.
                exit
            else
                error stop 'Read error'
            end if
        end if
    end do
    end function read_line
Call graph
go calls read_line, read_file_to_char_array
initialize calls read_line
read_file_to_char_array calls read_line
read_file_to_int_array calls read_line
problem_1 calls read_line
problem_12b calls read_line
problem_13 calls read_line
problem_15 calls read_line
problem_19 calls read_line
problem_19b calls read_line
problem_2 calls read_line
problem_24 calls read_line
problem_25 calls read_line
problem_4 calls read_line
problem_5 calls read_line
problem_7 calls read_line
problem_8 calls read_line
problem_9 calls read_line
problem_10 calls read_file_to_char_array
problem_12 calls go
problem_16 calls read_file_to_char_array
problem_17 calls read_file_to_int_array
problem_18 calls go
problem_21 calls read_file_to_char_array
problem_22 calls initialize
problem_3 calls read_file_to_char_array
problem_11 calls go
problem_23 calls go