sort_ascending_64 – AoC-2023
sort_ascending_64 Subroutine
45 statements
Source File
private subroutine sort_ascending_64(ivec)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(inout), dimension(:) :: ivec
Calls
Called by
Source Code
    subroutine sort_ascending_64(ivec)
    integer(int64),dimension(:),intent(inout) :: ivec
    integer(int64),parameter :: max_size_for_insertion_sort = 20 !! max size for using insertion sort.
    call quicksort(1_int64,size(ivec,kind=int64))
    contains
        recursive subroutine quicksort(ilow,ihigh)
        !! Sort the array
        integer(int64),intent(in) :: ilow
        integer(int64),intent(in) :: ihigh
        integer(int64) :: ipivot !! pivot element
        integer(int64) :: i      !! counter
        integer(int64) :: j      !! counter
        if ( ihigh-ilow<=max_size_for_insertion_sort .and. ihigh>ilow ) then
            ! do insertion sort:
            do i = ilow + 1,ihigh
                do j = i,ilow + 1,-1
                    if ( ivec(j) < ivec(j-1) ) then
                        call swap64(ivec(j),ivec(j-1))
                    else
                        exit
                    end if
                end do
            end do
        elseif ( ihigh-ilow>max_size_for_insertion_sort ) then
            ! do the normal quicksort:
            call partition(ilow,ihigh,ipivot)
            call quicksort(ilow,ipivot - 1)
            call quicksort(ipivot + 1,ihigh)
        end if
        end subroutine quicksort
        subroutine partition(ilow,ihigh,ipivot)
        !! Partition the array, based on the
        !! lexical ivecing comparison.
        implicit none
        integer(int64),intent(in)  :: ilow
        integer(int64),intent(in)  :: ihigh
        integer(int64),intent(out) :: ipivot
        integer(int64) :: i,ip
        call swap64(ivec(ilow),ivec((ilow+ihigh)/2))
        ip = ilow
        do i = ilow + 1, ihigh
            if ( ivec(i) < ivec(ilow) ) then
                ip = ip + 1
                call swap64(ivec(ip),ivec(i))
            end if
        end do
        call swap64(ivec(ilow),ivec(ip))
        ipivot = ip
        end subroutine partition
    end subroutine sort_ascending_64
Call graph
sort_ascending_64 calls swap64
sort calls sort_ascending_64
unique32 calls sort
unique64 calls sort
unique calls unique32, unique64
get_pieces_above calls unique
get_pieces_below calls unique
hand_type calls unique
beats calls hand_type
move_piece_down calls get_pieces_below
problem_22 calls get_pieces_above, get_pieces_below, move_piece_down
problem_7 calls beats