sort_ascending – AoC-2023
sort_ascending Subroutine
45 statements
Source File
private subroutine sort_ascending(ivec)
Sorts an integer array ivec in increasing order. Uses a basic recursive quicksort (with insertion sort for partitions with 20 elements).
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), dimension(:) :: ivec
Calls
Called by
Source Code
    subroutine sort_ascending(ivec)
    integer,dimension(:),intent(inout) :: ivec
    integer,parameter :: max_size_for_insertion_sort = 20 !! max size for using insertion sort.
    call quicksort(1,size(ivec))
    contains
        recursive subroutine quicksort(ilow,ihigh)
        !! Sort the array
        integer,intent(in) :: ilow
        integer,intent(in) :: ihigh
        integer :: ipivot !! pivot element
        integer :: i      !! counter
        integer :: j      !! counter
        if ( ihigh-ilow<=max_size_for_insertion_sort .and. ihigh>ilow ) then
            ! do insertion sort:
            do i = ilow + 1,ihigh
                do j = i,ilow + 1,-1
                    if ( ivec(j) < ivec(j-1) ) then
                        call swap(ivec(j),ivec(j-1))
                    else
                        exit
                    end if
                end do
            end do
        elseif ( ihigh-ilow>max_size_for_insertion_sort ) then
            ! do the normal quicksort:
            call partition(ilow,ihigh,ipivot)
            call quicksort(ilow,ipivot - 1)
            call quicksort(ipivot + 1,ihigh)
        end if
        end subroutine quicksort
        subroutine partition(ilow,ihigh,ipivot)
        !! Partition the array, based on the
        !! lexical ivecing comparison.
        implicit none
        integer,intent(in)  :: ilow
        integer,intent(in)  :: ihigh
        integer,intent(out) :: ipivot
        integer :: i,ip
        call swap(ivec(ilow),ivec((ilow+ihigh)/2))
        ip = ilow
        do i = ilow + 1, ihigh
            if ( ivec(i) < ivec(ilow) ) then
                ip = ip + 1
                call swap(ivec(ip),ivec(i))
            end if
        end do
        call swap(ivec(ilow),ivec(ip))
        ipivot = ip
        end subroutine partition
    end subroutine sort_ascending
Call graph
sort_ascending calls swap
swap calls swap32, swap64, swap_str
sort calls sort_ascending
unique32 calls sort
unique64 calls sort
unique calls unique32, unique64
get_all_pieces_above calls unique, get_all_pieces_above, get_pieces_above
get_all_pieces_below calls unique, get_all_pieces_below, get_pieces_below
get_pieces_above calls unique
get_pieces_below calls unique
hand_type calls unique
problem_25 calls unique
beats calls hand_type
move_piece_down calls get_pieces_below
problem_22 calls get_all_pieces_above, get_all_pieces_below, get_pieces_above, get_pieces_below, initialize
drop calls move_piece_down
problem_7 calls beats
initialize calls drop