split1 – AoC-2023
split1 Function
61 statements
Source File
private pure function split1(str, token) result(vals)
Split a character string using a token. This routine is inspired by the Python split function.
Example
   character(len=:),allocatable :: s
   type(string),dimension(:),allocatable :: vals
   s = '1,2,3,4,5'
   call split(s,',',vals)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
character(len=*), intent(in) :: token
Return Value type(string), dimension(:), allocatable
Calls
Called by
Source Code
    pure function split1(str,token) result(vals)
    implicit none
    character(len=*),intent(in)  :: str
    character(len=*),intent(in)  :: token
    type(string),dimension(:),allocatable :: vals
    integer :: i          !! counter
    integer :: len_str    !! significant length of `str`
    integer :: len_token  !! length of the token
    integer :: n_tokens   !! number of tokens
    integer :: i1         !! index
    integer :: i2         !! index
    integer :: j          !! counters
    integer,dimension(:),allocatable :: itokens !! start indices of the
                                                !! token locations in `str`
    len_token = len(token)  ! length of the token
    n_tokens  = 0           ! initialize the token counter
    j         = 0           ! index to start looking for the next token
    ! first, count the number of times the token
    ! appears in the string, and get the token indices.
    !
    ! Examples:
    !  ',         '    --> 1
    !  '1234,67,90'    --> 5,8
    !  '123,      '    --> 4
    ! length of the string
    if (token == ' ') then
        ! in this case, we can't ignore trailing space
        len_str = len(str)
    else
        ! safe to ignore trailing space when looking for tokens
        len_str = len_trim(str)
    end if
    j = 1
    n_tokens = 0
    do
        if (j>len_str) exit      ! end of string, finished
        i = index(str(j:),token) ! index of next token in remaining string
        if (i<=0) exit           ! no more tokens found
        call expand_vector(itokens,n_tokens,i+j-1)  ! save the token location
        j = j + i + (len_token - 1)
    end do
    call expand_vector(itokens,n_tokens,finished=.true.)  ! resize the vector
    allocate(vals(n_tokens+1))
    if (n_tokens>0) then
        len_str = len(str)
        i1 = 1
        i2 = itokens(1)-1
        if (i2>=i1) then
            vals(1)%str = str(i1:i2)
        else
            vals(1)%str = ''  !the first character is a token
        end if
        !      1 2 3
        !    'a,b,c,d'
        do i=2,n_tokens
            i1 = itokens(i-1)+len_token
            i2 = itokens(i)-1
            if (i2>=i1) then
                vals(i)%str = str(i1:i2)
            else
                vals(i)%str = ''  !empty element (e.g., 'abc,,def')
            end if
        end do
        i1 = itokens(n_tokens) + len_token
        i2 = len_str
        if (itokens(n_tokens)+len_token<=len_str) then
            vals(n_tokens+1)%str = str(i1:i2)
        else
            vals(n_tokens+1)%str = ''  !the last character was a token
        end if
    else
        !no tokens present, so just return the original string:
        vals(1)%str = str
    end if
    end function split1
Call graph
split1 calls expand_vector
split calls split1, split2
split2 calls split1
go calls split
parse_nums64 calls split
parse_rule calls split
problem_12b calls split
problem_15 calls split
problem_19 calls split, parse_rule
problem_19b calls split, parse_rule
problem_2 calls split
problem_24 calls split
problem_4 calls split
problem_7 calls split
parse calls parse_nums64
problem_12 calls go
problem_18 calls go
problem_9 calls parse