split2 – AoC-2023
split2 Function
11 statements
Source File
private pure function split2(s, token) result(vals)
Split a string, given a token.
Arguments
Type Intent Optional Attributes Name
type(string), intent(in) :: s
character(len=*), intent(in) :: token
Return Value type(string), dimension(:), allocatable
Calls
Called by
Source Code
    pure function split2(s,token) result(vals)
    implicit none
    type(string),intent(in)  :: s
    character(len=*),intent(in)  :: token
    type(string),dimension(:),allocatable:: vals
    if (allocated(s%str)) then
        vals = split1(s%str,token)
    else
        error stop 'error: string not allocated'
    end if
    end function split2
Call graph
split2 calls split1
split1 calls expand_vector
split calls split2
go calls split
initialize calls split
parse_nums64 calls split
parse_rule calls split
problem_12b calls split
problem_15 calls split
problem_19 calls split, parse_rule
problem_19b calls split, parse_rule
problem_2 calls split
problem_24 calls split
problem_25 calls split
problem_4 calls split
problem_7 calls split
parse calls parse_nums64
problem_12 calls go
problem_18 calls go
problem_22 calls initialize
problem_9 calls parse