startswith_cc – AoC-2023
startswith_cc Function
4 statements
Source File
private pure function startswith_cc(str, substring)
starts with function for strings
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
character(len=*), intent(in) :: substring
Return Value logical
Called by
Source Code
    pure logical function startswith_cc(str, substring)
        character(len=*),intent(in) :: str, substring
        startswith_cc = index(str, substring) == 1
    end function startswith_cc
Call graph
startswith calls startswith_cc, startswith_cs, startswith_sc, startswith_ss
startswith_cs calls startswith
startswith_sc calls startswith
startswith_ss calls startswith
problem_5 calls startswith