swap32 – AoC-2023
swap32 Subroutine
8 statements
Source File
private pure elemental subroutine swap32(i1, i2)
Swap two integer values.
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: i1
integer, intent(inout) :: i2
Called by
Source Code
    pure elemental subroutine swap32(i1,i2)
    integer,intent(inout) :: i1
    integer,intent(inout) :: i2
    integer :: tmp
    tmp = i1
    i1  = i2
    i2  = tmp
    end subroutine swap32
Call graph
swap calls swap32
sort_ascending calls swap
sort calls sort_ascending
unique32 calls sort
unique64 calls sort
unique calls unique32, unique64
hand_type calls unique
beats calls hand_type
problem_7 calls beats