swap64 – AoC-2023
swap64 Subroutine
8 statements
Source File
private pure elemental subroutine swap64(i1, i2)
Swap two integer values.
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(inout) :: i1
integer(kind=int64), intent(inout) :: i2
Called by
Source Code
    pure elemental subroutine swap64(i1,i2)
    integer(int64),intent(inout) :: i1
    integer(int64),intent(inout) :: i2
    integer(int64) :: tmp
    tmp = i1
    i1  = i2
    i2  = tmp
    end subroutine swap64
Call graph
swap calls swap64
sort_ascending_64 calls swap64
sort calls sort_ascending_64, sort_ascending
sort_ascending calls swap
unique32 calls sort
unique64 calls sort
unique calls unique32, unique64
hand_type calls unique
beats calls hand_type
problem_7b calls beats