unique64 – AoC-2023
unique64 Function
18 statements
Source File
private function unique64(vec) result(vec_unique)
Return only the unique values from vec.
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in), dimension(:) :: vec
Return Value integer(kind=int64), dimension(:), allocatable
Calls
Called by
Source Code
    function unique64(vec) result(vec_unique)
        integer(int64),dimension(:),intent(in) :: vec
        integer(int64),dimension(:),allocatable :: vec_unique
        integer(int64) :: i,num
        logical,dimension(size(vec)) :: mask
        mask = .false.
        do i=1,size(vec)
            !count the number of occurrences of this element:
            num = count( vec(i)==vec )
            if (num==1) then
                !there is only one, flag it:
                mask(i) = .true.
            else
                !flag this value only if it hasn't already been flagged:
                if (.not. any(vec(i)==vec .and. mask) ) mask(i) = .true.
            end if
        end do
        !return only flagged elements:
        allocate( vec_unique(count(mask)) )
        vec_unique = pack( vec, mask )
        ! also sort it:
        call sort(vec_unique)
    end function unique64
Call graph
unique64 calls sort
sort calls sort_ascending, sort_ascending_64
sort_ascending calls swap
sort_ascending_64 calls swap64
swap calls swap64, swap32, swap_str
unique calls unique64
hand_type calls unique
beats calls hand_type
problem_7 calls beats