update_array – AoC-2023
update_array Subroutine
7 statements
Source File
subroutine update_array()
populate the array using the start/end indices
Arguments
None
Called by
Source Code
    subroutine update_array()
        !! populate the array using the start/end indices
        integer :: i
        array = 0
        do i = 1, n_lines
            array(istart_array(i,1):iend_array(i,1),&
                  istart_array(i,2):iend_array(i,2),&
                  istart_array(i,3):iend_array(i,3)) = i
        end do
    end subroutine update_array
Call graph
move_piece_down calls update_array
problem_22 calls update_array, move_piece_down