vector_djb_hash – AoC-2023
vector_djb_hash Function
9 statements
Source File
private pure function vector_djb_hash(r) result(hash)
DJB hash algorithm for a integer(ip) vector.
See also
J. Shahbazian, Fortran hashing algorithm, July 6, 2013 Fortran Dev
Arguments
Type Intent Optional Attributes Name
integer(kind=ip), intent(in), dimension(:) :: r
the vector
Return Value integer(kind=ip)
the hash value
Called by
Source Code
    pure function vector_djb_hash(r) result(hash)
    integer(ip),dimension(:),intent(in) :: r     !! the vector
    integer(ip)                         :: hash  !! the hash value
    integer :: i !! counter
    hash = 5381_ip
    do i=1,size(r)
        hash = ishft(hash,5_ip) + hash + r(i)
    end do
    end function vector_djb_hash
Call graph
get_from_cache calls vector_djb_hash
get_all_pieces_above calls get_from_cache, get_all_pieces_above
get_all_pieces_below calls get_from_cache, get_all_pieces_below
go calls get_from_cache, ipoint, ipound
index_in_queue calls get_from_cache
check calls index_in_queue
ipoint calls go
ipound calls go
problem_12b calls go
problem_22 calls get_all_pieces_above, get_all_pieces_below
problem_17 calls check