int – AoC-2023
int Interface
3 statements
Source File
public interface int
Calls
Module Procedures
private pure elemental function string_to_int(me) result(i)
Basic string to integer routine
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: me
Return Value integer
private pure function char_to_int(str) result(i)
Basic string to integer routine
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
Return Value integer
private pure function char_to_int64(str, kind) result(i)
Basic string to integer(ip) routine. Hacky hack just so we can overload as int()
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer, intent(in) :: kind
Return Value integer(kind=int64)
private pure function char_array_to_int(str_array) result(i)
Character array to integer routine
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in), dimension(:) :: str_array
example ['1','3'] --> 13
Return Value integer
Call graph
int calls char_array_to_int, char_to_int, char_to_int64, string_to_int
char_array_to_int calls char_to_int