parse – AoC-2023
parse Interface
3 statements
Source File
public interface parse
Calls
Called by
Module Procedures
private function parse_nums64(line) result(ints)
parse space-deliminated int64 sequence (positive or negative)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: line
Return Value integer(kind=int64), dimension(:), allocatable
Call graph
parse calls parse_nums64
parse_nums64 calls split
split calls split1, split2
split1 calls expand_vector
split2 calls split1
problem_9 calls parse