sort – AoC-2023
sort Interface
3 statements
Source File
public interface sort
Calls
Called by
Module Procedures
private subroutine sort_ascending(ivec)
Sorts an integer array ivec in increasing order. Uses a basic recursive quicksort (with insertion sort for partitions with 20 elements).
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), dimension(:) :: ivec
private subroutine sort_ascending_64(ivec)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(inout), dimension(:) :: ivec
Call graph
sort calls sort_ascending, sort_ascending_64
sort_ascending calls swap
sort_ascending_64 calls swap64
swap calls swap64, swap32, swap_str
unique32 calls sort
unique64 calls sort
unique calls unique32, unique64
get_pieces_above calls unique
get_pieces_below calls unique
hand_type calls unique
beats calls hand_type
move_piece_down calls get_pieces_below
problem_22 calls get_pieces_above, get_pieces_below, move_piece_down
problem_7 calls beats