split – AoC-2023
split Interface
3 statements
Source File
public interface split
Calls
Called by
Module Procedures
private pure function split1(str, token) result(vals)
Split a character string using a token. This routine is inspired by the Python split function.
Read more…
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
character(len=*), intent(in) :: token
Return Value type(string), dimension(:), allocatable
private pure function split2(s, token) result(vals)
Split a string, given a token.
Arguments
Type Intent Optional Attributes Name
type(string), intent(in) :: s
character(len=*), intent(in) :: token
Return Value type(string), dimension(:), allocatable
Call graph
split calls split1, split2
split1 calls expand_vector
split2 calls split1
go calls split
initialize calls split
parse_nums64 calls split
parse_rule calls split
problem_12b calls split
problem_15 calls split
problem_19 calls split, parse_rule
problem_19b calls split, parse_rule
problem_2 calls split
problem_25 calls split
problem_4 calls split
problem_7 calls split
parse calls parse_nums64
problem_12 calls go
problem_18 calls go
problem_22 calls initialize
problem_9 calls parse