startswith – AoC-2023
startswith Interface
3 statements
Source File
public interface startswith
test if a string starts with a specified substring
Calls
Called by
Module Procedures
private pure function startswith_cc(str, substring)
starts with function for strings
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
character(len=*), intent(in) :: substring
Return Value logical
private pure function startswith_ss(str, substring)
Arguments
Type Intent Optional Attributes Name
type(string), intent(in) :: str
type(string), intent(in) :: substring
Return Value logical
private pure function startswith_sc(str, substring)
Arguments
Type Intent Optional Attributes Name
type(string), intent(in) :: str
character(len=*), intent(in) :: substring
Return Value logical
private pure function startswith_cs(str, substring)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
type(string), intent(in) :: substring
Return Value logical
Call graph
startswith calls startswith_cc, startswith_cs, startswith_sc, startswith_ss
startswith_cs calls startswith
startswith_sc calls startswith
startswith_ss calls startswith
problem_5 calls startswith