swap – AoC-2023
swap Interface
3 statements
Source File
public interface swap
Calls
Called by
Module Procedures
private pure elemental subroutine swap32(i1, i2)
Swap two integer values.
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: i1
integer, intent(inout) :: i2
private pure elemental subroutine swap64(i1, i2)
Swap two integer values.
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(inout) :: i1
integer(kind=int64), intent(inout) :: i2
private pure elemental subroutine swap_str(i1, i2)
Swap two character string values
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: i1
character(len=*), intent(inout) :: i2
Call graph
swap calls swap32, swap64, swap_str
sort_ascending calls swap
sort calls sort_ascending
unique32 calls sort
unique64 calls sort
unique calls unique32, unique64
hand_type calls unique
beats calls hand_type
problem_7b calls beats