unique – AoC-2023
unique Interface
3 statements
Source File
public interface unique
Calls
Called by
Module Procedures
private function unique32(vec) result(vec_unique)
Return only the unique values from vec.
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:) :: vec
Return Value integer, dimension(:), allocatable
private function unique64(vec) result(vec_unique)
Return only the unique values from vec.
Arguments
Type Intent Optional Attributes Name
integer(kind=ip), intent(in), dimension(:) :: vec
Return Value integer(kind=ip), dimension(:), allocatable
Call graph
unique calls unique32, unique64
unique32 calls sort
unique64 calls sort
sort calls sort_ascending, sort_ascending_64
sort_ascending calls swap
sort_ascending_64 calls swap64
swap calls swap64, swap32, swap_str
get_all_pieces_above calls unique, get_all_pieces_above, get_pieces_above
get_all_pieces_below calls unique, get_all_pieces_below, get_pieces_below
get_pieces_above calls unique
get_pieces_below calls unique
hand_type calls unique
problem_25 calls unique
beats calls hand_type
move_piece_down calls get_pieces_below
problem_22 calls get_all_pieces_above, get_all_pieces_below, get_pieces_above, get_pieces_below, initialize
drop calls move_piece_down
problem_7 calls beats
initialize calls drop