unique – AoC-2023
unique Interface
3 statements
Source File
public interface unique
Calls
Called by
Module Procedures
private function unique32(vec) result(vec_unique)
Return only the unique values from vec.
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:) :: vec
Return Value integer, dimension(:), allocatable
private function unique64(vec) result(vec_unique)
Return only the unique values from vec.
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in), dimension(:) :: vec
Return Value integer(kind=int64), dimension(:), allocatable
Call graph
unique calls unique32, unique64
unique32 calls sort
unique64 calls sort
sort calls sort_ascending, sort_ascending_64
sort_ascending calls swap
sort_ascending_64 calls swap64
swap calls swap64, swap32, swap_str
get_pieces_above calls unique
get_pieces_below calls unique
hand_type calls unique
beats calls hand_type
move_piece_down calls get_pieces_below
problem_22 calls get_pieces_above, get_pieces_below, move_piece_down
problem_7 calls beats