main – AoC-2023
main Program
5 statements
Source File
Uses
lsqrtest_module
Main program for tests.
Calls
Source Code
    program main
    use lsqrtest_module, only: lsqr_test
    implicit none
    call lsqr_test()
    end program main
Call graph
main calls lsqr_test
lsqr_test calls test
test calls 4, acheck, dcopy, dnrm2, lsqr, lstp, xcheck
acheck calls dcopy, dnrm2, aprod, ddot, dscal
lsqr calls dcopy, dnrm2, aprod, d2norm, dscal
lstp calls dcopy, dnrm2, aprod1, dscal, hprod
xcheck calls dcopy, dnrm2, aprod, dscal
aprod1 calls hprod